name       : faudio
version    : '20.01'
release    : 4
source     :
    - https://github.com/FNA-XNA/FAudio/archive/20.01.tar.gz : c015f7d395cf24b9050135238de38683e5a90378215bc6d5bb89777a9623f0e6
license    : Zlib
component  : multimedia.library
summary    : FAudio - Accuracy-focused XAudio reimplementation for open platforms
description: |
    XAudio reimplementation that focuses solely on developing fully accurate DirectX Audio runtime libraries for the FNA project, including XAudio2, X3DAudio, XAPO, and XACT3.
builddeps  :
    - pkgconfig32(sdl2)
emul32     : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
