name       : faudio
version    : '21.07'
release    : 8
source     :
    - https://github.com/FNA-XNA/FAudio/archive/refs/tags/21.07.tar.gz : 30738397354d27b32e03aea648d5f8ba7ff6a63e02282b8f1533a44af2ba06b3
license    : Zlib
component  : multimedia.library
summary    : FAudio - Accuracy-focused XAudio reimplementation for open platforms
description: |
    XAudio reimplementation that focuses solely on developing fully accurate DirectX Audio runtime libraries for the FNA project, including XAudio2, X3DAudio, XAPO, and XACT3.
builddeps  :
    - pkgconfig32(sdl2)
emul32     : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
