name       : faudio
version    : '21.11'
release    : 10
source     :
    - https://github.com/FNA-XNA/FAudio/archive/refs/tags/21.11.tar.gz : 1389100ca132e06455ad7e4e765a045d9821c234f6e388bef6a0c8d610ce36d1
license    : Zlib
component  : multimedia.library
summary    : FAudio - Accuracy-focused XAudio reimplementation for open platforms
description: |
    XAudio reimplementation that focuses solely on developing fully accurate DirectX Audio runtime libraries for the FNA project, including XAudio2, X3DAudio, XAPO, and XACT3.
builddeps  :
    - pkgconfig32(sdl2)
emul32     : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
