name       : faudio
version    : '21.10'
release    : 9
source     :
    - https://github.com/FNA-XNA/FAudio/archive/refs/tags/21.10.tar.gz : eca3e2cc148f9b25e8ce61153f3f552a385cdaa903f691af0a53932cc10cfb39
license    : Zlib
component  : multimedia.library
summary    : FAudio - Accuracy-focused XAudio reimplementation for open platforms
description: |
    XAudio reimplementation that focuses solely on developing fully accurate DirectX Audio runtime libraries for the FNA project, including XAudio2, X3DAudio, XAPO, and XACT3.
builddeps  :
    - pkgconfig32(sdl2)
emul32     : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
